Fix firewall validation and resource group output

diff --git a/scripts/loopback-fw-validate b/scripts/loopback-fw-validate
--- a/scripts/loopback-fw-validate
+++ b/scripts/loopback-fw-validate
@@ -10,6 +10,6 @@ INTF=$1
 
 if [ "$INTF" != "lo" ]
 then
-	>2& echo "Failed: Firewalls can only be assigned to 'lo'"
+	echo "Failed: Firewalls can only be assigned to 'lo'" >&2
 	exit 1
 fi
